apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-application-production
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mtl-test
    name: in-cluster # EKS cluster arn
  project: default
  syncPolicy:
    automated:
      prune: false 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: helm
    repoURL: https://github.com/PoomKrit/mtl-test.git
    targetRevision: HEAD
    helm:
      releaseName: 'go-application'
      valueFiles: ['values-production.yaml']
